In [1]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.75, 1.80, 1.65])
np_weight = np.array([65.0, 70.0, 75.0, 80.0, 60.0])

np_height

array([1.73, 1.68, 1.75, 1.8 , 1.65])

In [2]:
np_height + np_weight  # This will raise an error since they have different shapes

array([66.73, 71.68, 76.75, 81.8 , 61.65])

In [3]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [5]:
def fib(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)
    
num = 10
for i in range(num):
    print(fib(i), end=' ')


0 1 1 2 3 5 8 13 21 34 

In [ ]:
height = [1.4, 1.8, 1.6, 1.2, 1.5]

weight = [79, 80, 50, 49, 63]

print(height + weight)

# To see just the first element in a list 
print(height[0])

# To print the last element in a list
print(height[-1])

# To print a slice of a list
print(height[4,9])

[1.4, 1.8, 1.6, 1.2, 1.5, 79, 80, 50, 49, 63]
1.4
1.5


In [12]:
print(height[4:])

[1.5]


In [17]:
Elements = height + weight
print(Elements[4:])

Elements.insert(11,19)
print(Elements)
Elements.append(12)
print(Elements)

[1.5, 79, 80, 50, 49, 63]
[1.4, 1.8, 1.6, 1.2, 1.5, 79, 80, 50, 49, 63, 19]
[1.4, 1.8, 1.6, 1.2, 1.5, 79, 80, 50, 49, 63, 19, 12]


In [ ]:
areas = ['hall1',400,['Harry', 'Larenta', 'Darius'],'hall2',350,['Marian','Jones'],'hall3',250]
print(areas[3])

areas[3] = 352

areas

350


['hall1', 400, 'hall2', 352, 'hall3', 250]

In [30]:
areas = ['hall1',400,['Harry', 'Larenta', 'Darius'],'hall2',350,['Marian','Jones'],'hall3',250]
print(areas[2][0])

print(f'My name is {areas[2][0]}')
print(f'the area of {areas[3]} is {areas[4]} cm2')

Harry
My name is Harry
the area of hall2 is 350 cm2


In [34]:
areas = ['hall1',400,['Harry', 'Larenta', 'Darius'],'hall2',350,['Marian','Jones'],'hall3',250]

areas = areas[::-1]
print(areas)

[250, 'hall3', ['Marian', 'Jones'], 350, 'hall2', ['Harry', 'Larenta', 'Darius'], 400, 'hall1']


In [45]:
house1 = ['poolhouse',500]
house2 = ['hall',550]
house3 = ['garage',650]

myhouse = house1 + house2 + house3



# print(copy_house1)

copy_house1[0] = 'room'



copy_house1 = list(house1)
copy_house1[0] = 'room'
print(house1)
print(copy_house1)

copy_house2 = house1.copy()

copy_house2[1] = 4000
print(copy_house2,house1)


['poolhouse', 500]
['room', 500]
['poolhouse', 4000] ['poolhouse', 500]


In [48]:
def calc_bmi(wei,hei):
    return hei/(wei**2)

height = [1.4, 1.8, 1.6, 1.2, 1.5]

weight = [79, 80, 50, 49, 63]


print(calc_bmi(62,1.95))
print(calc_bmi(42,1.8))

0.0005072840790842872
0.0010204081632653062


In [65]:
village = 'Bakaiju1aqqambat'
village1 = ['n','k','o','n','g','s','a','m','b','a']
n = 0
for i in range(len(village)):
    if village[i] == 'a':
        n = n+1
        print(f'n is now {n}')
print(n)

# print(village[3])
# print(village1[3])


n is now 1
n is now 2
n is now 3
n is now 4
n is now 5
5


In [55]:
for letter in range(21):
    print(letter)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [68]:
import math 

math.pi

radius = 5


area = math.pi*radius**2

print(area)

78.53981633974483


In [82]:
import re

x = re.search("^B",village)

if x:
    print("Yes it is present")
else:
    print("not found")




#  ^  To check whther a sting starts with a specific expression
#  $ To check whther a sting end with a specific expression




Yes it is present


In [90]:
matricule = 'UBa23R0290'

name = 'Berinyuy'

if re.search("y$", name):
    print("yes it begins")

else:
    print("Not present")


# B != b

yes it begins


In [ ]:
areas = ['hall1',400,['Harry', 'Larenta', 'Darius'],'hall2',350,['Marian','Jones'],'hall3',250]
print(areas[3])

areas[3] = 352

areas

350


['hall1', 400, 'hall2', 352, 'hall3', 250]