In [1]:
for i in range(1,10,1):
    print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
while i%2 ==0:
    print(i)
    i += 1

In [3]:
def printNew(name):
    print(name)



printNew("Hannah")

Hannah


In [6]:
printNew(56+34)

90


In [8]:
def inputNew():
    name = input("What is your name?")
    print("This is Elisha's Input Method, " + name)



inputNew()

This is Elisha's Input Method, yudk


In [11]:
def convertKelvin(celsius):
    return celsius + 273.15


print(convertKelvin(25))

298.15


In [ ]:
def convertKelvin2(celsius):
    kelvin = celsius + 273.15
    return kelvin


print(convertKelvin2(25))

In [13]:
def convertKelvin3(celsius):
    kelvin = celsius + 273
    print(kelvin)


convertKelvin3(0)

273


In [ ]:
def my_function(name): # name is a parameter
  print("Hello", name)

my_function("Emil") # "Emil" is an argument

In [15]:
def new_function(fname, lname):
    print(fname, lname)


new_function("Neba", "Edgar")


def new_function2(fname = "Neba"):
    print(fname)

new_function2()



Neba Edgar
Neba


In [17]:
def new_function2(fname = "Neba"):
    print(fname)

new_function2()




Neba


In [18]:
def tupleTolistConverter(mytuple):
    mylist = list(mytuple)
    return type(mylist)



use = ("Hannah", "Elisha", "Edgar")
tupleTolistConverter(use)



list

In [20]:
def dictionary(mydict):
    print(mydict)

In [21]:
students = {
    'name1': 'Hannah',
    'name2': 'Elisha',
    'name3': 'Edgar'
}


dictionary(students)

{'name1': 'Hannah', 'name2': 'Elisha', 'name3': 'Edgar'}


In [29]:
def multiply(*numbers):
    result = 1
    for number in numbers:
        result = result * number

    return result


print(multiply(190))

190


In [33]:
def numOrProduct(num1,*numbers):
    if len(numbers) == 0:
        return num1
    else:
        result = num1
    for number in numbers:
        result = result * number

    return result
    


print(numOrProduct(190,3,4,5))


11400


In [38]:
def add (numq, num2):
    print(numq + num2)
    print(numq + num2)
    print(numq + num2)




result = add(5, 10)

print(result)

15
15
15
None


In [ ]:
open("./files/test.txt",)#relative path

open("E:/Local Disk D/Data Science/Hort 6.0/files/test.txt",) #absolute path

open(r"E:\Local Disk D\Data Science\Hort 6.0\open.txt")



In [40]:
file = open(r"E:\Local Disk D\Data Science\Hort 6.0\files\test.txt","r")

print(file.read())

Elisha
Junior
Marcel
Edgar
Igan
Hannah
Sylvanus
Bright


In [45]:
file = open(r"E:\Local Disk D\Data Science\Hort 6.0\files\test.txt","a")

file.write("\nThis is a new line that was appended to the file")
file = open(r"E:\Local Disk D\Data Science\Hort 6.0\files\test.txt","r")

print(file.read())

Elisha
Junior
Marcel
Edgar
Igan
Hannah
Sylvanus
BrightThis is a new line that was appended to the fileThis is a new line that was appended to the file
This is a new line that was appended to the file
This is a new line that was appended to the file
This is a new line that was appended to the file


In [46]:
file = open(r"E:\Local Disk D\Data Science\Hort 6.0\files\test.txt","w")

file.write("Written line")

file = open(r"E:\Local Disk D\Data Science\Hort 6.0\files\test.txt","r")

print(file.read())

Written line


In [49]:
def Hannah_prime(num3 ):


    # number = int(input("Enter a number: "))

    mylist = []
    for i in range(1, num3+1):
        mylist.append(num3%i)


    if mylist.count(0) == 2:
        return True
    else:
        return False



In [54]:
i = 1
mylist = []
while len(mylist) <= 100:
    if Hannah_prime(i):
        mylist.append(i)
    i += 1

print(mylist)



[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547]


In [59]:
file = open(r"E:\Local Disk D\Data Science\Hort 6.0\files\primenumber3.txt","x")

file.write(str(mylist))

file = open(r"E:\Local Disk D\Data Science\Hort 6.0\files\primenumber3.txt","r")

print(file.read())

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547]


In [63]:
mylist = [1,2,3,4,5,6,7,8,9,10]
print(mylist)
newlist  = mylist * mylist
print(newlist)

for i in range(len(mylist)):
    mylist[i] *= mylist[i]


print(mylist)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


TypeError: can't multiply sequence by non-int of type 'list'

# **Numpy**

In [66]:
import numpy 

myArray = [number for number in range(1,100)]


numpy_array = numpy.array(myArray)

print(type(numpy_array))
print(type(myArray))


print(numpy_array * numpy_array)

<class 'numpy.ndarray'>
<class 'list'>
[   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764
 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025 3136
 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761 4900
 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889 7056
 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409 9604
 9801]


In [ ]:
newList = [1,2,3,4,5,6,7,8,9,10]

newList = numpy.array(newList)

print

In [82]:
import numpy as np

newlist1 = [1,2,3]
newlist2 = [4,5,6]
newlist3 = [7,8,9]

newlist_np = np.array([newlist1, newlist2,newlist3])


print(newlist_np)

print(newlist_np[2][2])
print(newlist_np[2,2])

print(newlist_np[1:3,1:3])


print(newlist_np[[4,5],[6,7]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
9
[[5 6]
 [8 9]]


IndexError: index 4 is out of bounds for axis 0 with size 3

In [ ]:
#2d array of number



In [83]:
new_list = [1,2,3,4,5,6,7,8,9]
newList_np = np.array(new_list)

print(newlist_np.reshape(3,3))

print(newlist_np.ndim)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [84]:
print(newlist_np.dtype)

int64


In [85]:
li = [1.1,1.2,1.3,1.4,1.5]
li_np = np.array(li)

print(li_np.dtype)

float64


In [87]:
myList = [1,2,3,4,5]

myList_np = np.array(myList, dtype = float)

print(myList_np.dtype)

float64


In [93]:
new_list = [1,2,3,4,5,6,7,8,9]

newList_np = np.array(new_list)

print(newlist_np.shape)
print(newlist_np.size)
print(newlist_np.ndim)

(3, 3)
9
2


In [104]:
print(np.empty((3,3)))

print(np.zeros((3,3)))

print(np.ones((3,3)))

print(np.full((6,6), 100))


list_np = np.full((6,6), 100)

x = [100, 100, 100, 100, 100, 100]

print( x in list_np.tolist())


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
True


In [ ]:
a = np.array([[10.5, 22.5, 3.8],
              [41, np.nan, np.nan]])


print(a)




[[10.5 22.5  3.8]
 [41.   nan  nan]]


In [ ]:
new_list = [1,2,3,4,5,6,7,8,9]

new_list_np = np.array(new_list)

# print(new_list)
print(new_list_np.mean())
print(np.median(new_list_np))
print(new_list_np.sum())


print(np.isfinite(a))



5.0
5.0
45
True
True


In [124]:
a = np.array([[10.5, 22.5, 3.8],
              [41, np.nan, np.nan]])


a[np.isnan(a)] = np.mean(a[np.isfinite(a)])

print(a)

# isnan()
# isfinite()

# a

[[10.5  22.5   3.8 ]
 [41.   19.45 19.45]]


In [125]:
a[np.isnan(a)]

array([], dtype=float64)